### ISSUE TITLE
CompletionItemKind is not shown in comletion list when typing multiple tokens

### ISSUE THREAD

**Issue by gasuketsu** [fannheyward/coc-pyright#665] opened 2021-11-24 13:06 UTC
When typing `from `, completion list shown w/o CompletionItemKind like below
![image](https://user-images.githubusercontent.com/15703757/143242797-2e3083d8-7a87-4fcb-8f48-2fdbd85fcbaa.png)

Just typing `from ` and leave insert mode, then going back to insert mode and list completion list again, we get candidates with CompletionItemKind as below.
![image](https://user-images.githubusercontent.com/15703757/143243530-74ef7a33-fe7f-4a6c-a4d0-87d86745c524.png)

I assume that CompletionItemKind should be shown in completion list even if typing several tokens at a time, but is current behavior is expected one ?

**What's the output of `:CocCommand pyright.version`**

[coc.nvim] coc-pyright 1.1.189 with Pyright 1.1.189

**What's the output of `:CocCommand workspace.showOutput Pyright`**

Workspace: /home/tharada/repos/foo
Using python from /home/tharada/repos/foo/.venv/bin/python

[Info  - 9:31:52 PM] Pyright language server 1.1.189 starting
[Info  - 9:31:52 PM] Server root directory: /home/tharada/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
[Info  - 9:31:52 PM] No configuration file found.
[Info  - 9:31:52 PM] No pyproject.toml file found.
[Info  - 9:31:52 PM] Setting pythonPath for service "foo": "/home/tharada/repos/foo/.venv/bin/python"
[Warn  - 9:31:52 PM] stubPath /home/tharada/repos/foo/typings is not a valid directory.
[Info  - 9:31:52 PM] Assuming Python version 3.10
[Info  - 9:31:52 PM] Assuming Python platform Linux
[Warn  - 9:31:52 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Warn  - 9:31:52 PM] Exception received when installing file system watcher: TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
[Info  - 9:31:52 PM] Searching for source files
[Info  - 9:31:52 PM] Auto-excluding /home/tharada/repos/foo/.venv
[Info  - 9:31:52 PM] No source files found.

**Comment by BoysHands** [comment] 2021-11-24 14:56
I have the same problem, and it seems the problem of priority of souces, python-import and pyright. When I disable python-import[PY] by "CocList Sources", it will get completion result from pyright[LS]. However, the source, python-import[PY], just can not be diabled by CocConfig, I have to close it when i enter a python file.

**Comment by fannheyward** [comment] 2021-11-25 02:08
@gasuketsu will improve the CompletionItemKind info.

@BoysHands why do you want to disable `python-import` source or what's the problem with it?

The `python-import` source is provided by coc-pyright with a little quick fix for the import issue:

1. try to disable `python-import` source in `:CocList sources`
2. input `import ` or `from `, there's not any imports suggestion
3. you need to trigger `coc#refresh()` to get suggestions

with `python-import`, coc-pyright will trigger the suggestions after input `space` after import/from.

**Comment by fannheyward** [comment] 2021-11-25 03:50
Try v1.1.190.

**Closed by fannheyward** 2021-11-25 03:50 UTC

**Comment by BoysHands** [comment] 2021-11-25 06:29
@fannheyward python-import may conflict with pyright.when i input ` import `, i will get suggestion from both python-import and pyright. And python-import can not cover all my modules, like ` sys ` module will not be listed by python-import.So i just like to get suggestion from pyright with higher priority.

**Comment by fannheyward** [comment] 2021-11-25 06:32
@BoysHands can you give me a screenshot of the conflict? The `python-import` is came from Pyright too.

**Comment by fannheyward** [comment] 2021-11-26 01:49
>  like sys module will not be listed by python-import

@BoysHands reproduced, but have no idea about this because the results of `python-import` is came from Pyright too. I'll add an option to disable `python-import`.
