### ISSUE TITLE
"Import could not be resolved" for newly created local module - pyright restart needed

### ISSUE THREAD

**Issue by mark-henry01** [fannheyward/coc-pyright#781] opened 2022-07-31 10:54 UTC
**What's the output of `:CocCommand pyright.version`**
[coc.nvim] coc-pyright 1.1.262 with Pyright 1.1.264

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Workspace: /home/user/python-test
Using python from /usr/bin/python
Pyright language server 1.1.264 starting
Server root directory: /home/user/.config/coc/extensions/node_modules/coc-pyright/node_modules/pyright/dist/
Starting service instance "python-test"
Setting pythonPath for service "python-test": "/usr/bin/python"
Loading configuration file at /home/user/python-test/pyrightconfig.json
Assuming Python version 3.10
Assuming Python platform Linux
No include entries specified; assuming /home/user/python-test
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /home/user/python-test/typings is not a valid directory.
Searching for source files
Found 2 source files
```

**Project**
```
mkdir python-test
cd python-test/
echo '{}' > pyrightconfig.json
```

```
[user@test-coc-pyright python-test]$ tree 
.
├── __pycache__
│   └── foo.cpython-310.pyc
├── foo.py
├── main.py
└── pyrightconfig.json
```

**Test environment (vanilla Fedora 36)**
```
mkdir -p ~/.local/share/nvim/site/pack/coc/start
cd ~/.local/share/nvim/site/pack/coc/start
git clone --branch release https://github.com/neoclide/coc.nvim.git --depth=1
node --version
#v16.16.0
npm --version
#8.11.0
:CocInstall coc-pyright
python --version
# Python 3.10.5
which python
# /usr/bin/python
```
**Error description**
Start nvim with some module:
```
nvim main.py
```
Create new module foo.py while nvim is opened:
```
:!touch foo.py
```
Typing inside: `main.py`
```
import foo
```
will trigger following error: 

> [Pyright reportMissingImports] [E] Import "foo" could not be resolved
> ─────────────────────────────────────────────────────────────────────
> https://github.com/microsoft/pyright/blob/main/docs/configuration.md 
> ─────────────────────────────────────────────────────────────────────
> [Pyright] [H] "foo" is not accessed       

**Workaround**
- Either restart nvim completely or restart pyright via (:CocList -> services -> pyright)
- - `pyright.restartserver` command does not help here

---

Why will be a newly created local module not recognized, until nvim or pyright is restarted? Thank you for help.

**Comment by fannheyward** [comment] 2022-08-01 11:03
Reproduced, but have no idea about this, because Pyright didn't recognize the newly created module.

You can use `:CocRestart` as a workaround.

**Comment by mark-henry01** [comment] 2022-08-02 11:50
VSCode/VSCodium + pyright recognizes added local modules properly, have just tried that.

@fannheyward Do you think, it is more of a pyright thing, so it make sense to ask for help in their repo?

**Comment by fannheyward** [comment] 2022-08-03 10:53
@mark-henry01 VSCode/VSCodium has file watching feature, I think this is the reason that editor can recognize newly created file. I'll dig this later.

**Comment by mark-henry01** [comment] 2022-09-09 07:22
Just stumbled on the [note about watchman](https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim#user-content-install-watchman-for-file-watching)  - it seems that underlying pyright [already supports](https://github.com/microsoft/pyright/search?q=didChangeWatchedFiles) the `didChangeWatchedFiles` feature.

Will try `watchman` installation next time I have a working python coc.nvim  environment. 
Would there be anything to do on coc-pyright side?

**Comment by fannheyward** [comment] 2023-05-31 08:23
@mark-henry01 I can't reproduce this anymore, can you reproduce this?

**Comment by yaegassy** [comment] 2023-05-31 09:38
@fannheyward It appears that the Pyright language server is dynamically adding watchers on the server side. Therefore, installing `watchman` may be necessary.

```
[Trace - 18:25:49.816] Received request 'client/registerCapability - (4)'.
Params: {
    "registrations": [
        {
            "id": "d52191d6-5f75-4aa1-87b4-fb553eb316ea",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**/pyrightconfig.json",
                        "kind": 7
                    },
                    {
                        "globPattern": "**",
                        "kind": 7
                    },
                    {
                        "globPattern": {
                            "baseUri": "file:///Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11",
                            "pattern": "**"
                        },
                        "kind": 7
                    }
                ]
            }
        }
    ]
}
```

If `watchman` is not installed in the environment, the `workspace/didChangeWatchedFiles` notification may not be received.

**Comment by fannheyward** [comment] 2023-07-11 08:09
Close this for now.

**Closed by fannheyward** 2023-07-11 08:09 UTC
