### ISSUE TITLE
Black formatting not working with language overrides

### ISSUE THREAD

**Issue by ravisumit33** [fannheyward/coc-pyright#951] opened 2023-06-14 10:08 UTC
**What's the output of `:CocCommand pyright.version`**
` coc-pyright 1.1.310 with Pyright 1.1.314 `

**What's the output of `:CocCommand workspace.showOutput Pyright`**
```
Using python from /Users/apple/.pyenv/shims/python

########## active formattor: black
execPath:   /Users/apple/.pyenv/shims/black
moduleName: undefined
args:       --diff,--quiet,-l 120,/Users/apple/pyscript.py.4ec83fcc87611cddcdf5eea266a120c0.py

########## black output:

########## black formatting action is canceled on success
```

It seems that black formatting actions is being cancelled and not being run. My python script is around 300 lines long and not that big. I checked https://github.com/fannheyward/coc-pyright/issues/229#issuecomment-794788144 and tried setting both `coc.preferences.willSaveHandlerTimeout` and `coc.preferences.formatOnSaveTimeout` to `5000` but action is still being cancelled. Tried setting these individually as well as both at the same time but no success.  I can manually do `:call CocAction('format')` to format the script successfully but I want to happen it on save.

Below is my coc config:
```
"[c][cpp][javascript][python]": {
    "coc.preferences.formatOnSave": true,
    "coc.preferences.formatOnSaveTimeout": 5000,
    "coc.preferences.willSaveHandlerTimeout": 5000
  },
```

If I apply above configurations globally it works.

**Comment by fannheyward** [comment] 2023-06-14 10:19
Do you have any `formatOnSaveTimeout` logs in `:CocOpenLog` ?

**Comment by ravisumit33** [comment] 2023-06-14 10:26
`Attempt to format file:///Users/apple/pyscript.py on save timed out after 500ms`

I can't understand how is this coming since I have already set it to 5000 ms in my config like below:
```
"[c][cpp][javascript][python]": {
    "coc.preferences.formatOnSave": true,
    "coc.preferences.formatOnSaveTimeout": 5000
  },
```
If I set it outside language overrides it works correctly and format the script.

**Comment by fannheyward** [comment] 2023-06-14 10:34
Reproduced, looks like something broken with language-override configuration didn't work.

**Comment by fannheyward** [comment] 2023-08-31 06:01
Has been fixed on coc.nvim.

**Closed by fannheyward** 2023-08-31 06:02 UTC
